### PR TITLE
Fix for missing message attributes

### PR DESCRIPTION
**Pull request by scatterbrain**
Incoming messages didn't include message attributes. This PR fixes that.

### CODE REVIEW

**Comment by peburrows** [comment]
Thanks, @scatterbrain. I'm happy to merge this, as it makes the test case better, but it doesn't appear to me that this actually changes any functionality. The only code change I see is renaming a variable. Am I missing something?

**Comment by scatterbrain** [comment]
There's a hard to notice change in the actual functionality as well. 

Whereas the old `mess` variable referenced the whole message structure given as a parameter, the new `message`variable references the `"message"` key within that parameter structure (`}}=mess)`vs `} = message })`).

The `attributes` map appears within the `message` map. This appears to be the structure when receiving messages from PubSub and with this change message attributes come through. Before the change attributes map was always empty.

**Comment by peburrows** [comment]
Ah, I see now! Thanks for pointing that out. I'll get this merged and a new release pushed soon.

**Comment by peburrows** [comment]
Just published `v0.3.1`: https://hex.pm/packages/kane/0.3.1

**Pull request merged**
